# This cargo deny file makes sure that for the Mac target, we don't take on OpenSSL
# deps for the normal (not build / dev) dependencies.

# It doesn't actually check for just normal deps right now:
# https://github.com/EmbarkStudios/cargo-deny/issues/563

all-features = false
no-default-features = false
targets = [
    { triple = "aarch64-apple-darwin" },
]

[advisories]
vulnerability = "allow"
unmaintained = "allow"
notice = "allow"
unsound = "allow"
yanked = "allow"

[licenses]
unlicensed = "allow"
copyleft = "allow"
default = "allow"

[bans]
multiple-versions = "allow"
wildcards = "allow"
workspace-default-features = "allow"
external-default-features = "allow"
# We need to make this only check for the normal deps, not build or dev.
deny = [
    { name = "openssl" },
    { name = "openssl-sys" },
    { name = "openssl-macros" },
]

[sources]
unknown-registry = "allow"
unknown-git = "allow"
