name: Rust Unit Tests
description: Runs all Rust unit tests
inputs:
  GIT_CREDENTIALS:
    description: "Optional credentials to pass to git. Useful if you need to pull private repos for dependencies"
    required: false
  partition:
    description: "The partition number for the tests"
    required: true

runs:
  using: composite
  steps:
    # Checkout the repository and setup the rust toolchain
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # get all the history because cargo xtest --change-since origin/main requires it.
    - uses: aptos-labs/aptos-core/.github/actions/rust-setup@main
      with:
        GIT_CREDENTIALS: ${{ inputs.GIT_CREDENTIALS }}

    # Check the VM features
    - name: Check VM features
      run: cargo test --profile ci --locked --features check-vm-features -p aptos-node
      shell: bash

    # Run the rust doc tests
    - name: Run rust doc tests
      run: cargo test --profile ci --locked --doc --workspace --exclude aptos-node-checker
      shell: bash

    # Install nextest
    - uses: taiki-e/install-action@v1.5.6
      with:
        tool: nextest

    # Run a postgres database
    - name: Run postgres database
      run: docker run --detach -p 5432:5432 cimg/postgres:14.2
      shell: bash

    - uses: actions/cache/restore@v3
      id: cache
      with:
        path: nextest-output
        key: cache-${{ github.run_id }}-${{ github.run_attempt }}

    # Run the rust unit tests
    - name: Run rust unit tests (partitioned)
      shell: bash
      run: cargo nextest run --archive-file nextest-output/nextest-archive.tar.zst --partition count:${{ inputs.partition }}/3  --retries 3 --no-fail-fast
      env:
        INDEXER_DATABASE_URL: postgresql://postgres@localhost/postgres
        RUST_MIN_STACK: 4297152
        MVP_TEST_ON_CI: true
        SOLC_EXE: /home/runner/bin/solc
        Z3_EXE: /home/runner/bin/z3
        CVC5_EXE: /home/runner/bin/cvc5
        DOTNET_ROOT: /home/runner/.dotnet
        BOOGIE_EXE: /home/runner/.dotnet/tools/boogie
