[package]
name = "NFTDAO"
version = "0.0.0"
upgrade_policy = "immutable"

[addresses]
dao_platform = "_"

[dependencies]
AptosFramework = { local = "../../../framework/aptos-framework" }
AptosToken = { local = "../../../framework/aptos-token" }
