apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "aptos-fullnode.fullname" . }}-fullnode
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fullnode
