[package]
name = "Upgradeable Module With Resource Account"
version = "0.0.0"
upgrade_policy = "compatible"

[addresses]
aptos_framework = "0x1"
deployer = "_"
upgradeable_resource_account_package = "_"

[dependencies]
AptosFramework = { local = "../../framework/aptos-framework" }
