[package]
name = "Upgradeable Resource Account Contract"
version = "0.0.0"
upgrade_policy = "compatible"

[addresses]
aptos_framework = "0x1"
deployer = "_"
upgradeable_resource_contract = "_"

[dependencies]
AptosFramework = { local = "../../framework/aptos-framework" }