%YAML 1.2
---

zkey_path: "/Users/rex/devnet-groth16-keys/main_c.zkey"
witness_gen_binary_folder_path: "/Users/rex/devnet-groth16-keys/main_c_cpp"
test_verification_key_path: "/Users/rex/devnet-groth16-keys/verification_key.json"
oidc_providers:
  - iss: "https://accounts.google.com"
    endpoint_url: "https://www.googleapis.com/oauth2/v3/certs"
jwk_refresh_rate_secs: 10
port: 8080
metrics_port: 9100
