apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "aptos-validator.fullname" . }}-validator
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: validator
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "aptos-validator.fullname" . }}-fullnode
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fullnode
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "aptos-validator.fullname" . }}-haproxy
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: haproxy
